on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: deploy to dockerhub
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Construye Imagen
        run: |
          echo "Building Docker image..."
          docker build -t cxayala/hola-mundo:8 .
      - name: Pushea Imagen
        run: |
          echo "Building Docker image..."
          docker push cxayala/hola-mundo:8
