on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: deploy to dockerhub
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.CXAS_USERNAME }}
          password: ${{ secrets.CXAS_SECRET }}
          
      - name: Construye Imagen
        run: |
          echo "Building Docker image..."
          docker build -t cxayala/hola-mundo:${{ github.run_number }} .
      - name: Pushea Imagen
        run: |
          echo "Pushing Docker image..."
          docker push cxayala/hola-mundo:${{ github.run_number }}
