on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: deploy to dockerhub
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Mostrar informacion
          run: |
            echo "Building construccion del docker"
            docker build -t cxayala/hola-mundo:1
